#! /usr/bin/env ruby

def usage
	puts "gendict INPUT OUTPUT"
end

#Check that the number of arguments match our requirement
if ARGV.length != 2
	usage
	puts "Not enough arguments"
	exit -1
end

puts "Generating #{ARGV[1]} from #{ARGV[0]}"

infile	= ARGV[0]
outfile	= ARGV[1]

#Check if the arguments were valid
if File.exists? outfile
	puts "error: outfile exists"
	exit -1
end
if not File.exists? infile
	puts "error: infile does not exist"
	exit -1
end

#Open both files
infile	= File.open infile, "r"
outfile	= File.open outfile, "w"

#Initialize our reference table
operands = []

puts "Reading operands..."
#Read file data that we need
infile.each do |line|
	line = line.chomp

	#Remove repeated tabs
	for i in 0...10
		line.gsub! "\t\t", "\t"
	end
	
	#Add operand
	operands.push(line.split "\t")
end

#We are finished with infile
infile.close

header_name = ARGV[1].upcase.gsub ".", "_"
outfile.puts "#ifndef #{header_name}"
outfile.puts "#define #{header_name}\n"

puts "Defining operands..."
#Define all of the operands
count = 0
operands.each do |op|
	outfile.puts "#define  #{op[0].upcase} #{count}"
	count += 1
end

#Insert a newline
outfile.puts

outfile.puts "#define NUM_OPS #{count}\n"

#Create start of string reference table
outfile.print "char** op_str_val = { "

puts "Creating string table..."
#Fill in table
operands.each do |op|
	outfile.print '"'
	outfile.print "#{op[0]}"
	outfile.print '", '
end

#End string table
outfile.puts "};"

#Create start of length reference table
outfile.print "int op_len_val[] = { "

puts "Creating length table..."
#Fill in table
operands.each do |op|
	outfile.print "#{op[1]}, "
end

#End length table
outfile.puts "};\n"

outfile.puts "#endif"

outfile.close

puts "Header generation for #{ARGV[0]} complete."
